######################################################################
# Automatically generated by qmake (3.0) Thu Jul 28 11:17:33 2016
######################################################################

TEMPLATE = app
TARGET = offscreen2texture-qt
INCLUDEPATH += . /home/ybin/usrfs/include
LIBS += -lEGL

QT += gui

# Input
SOURCES += main.cpp
